apiVersion: v1
kind: Service
metadata:
  name: claims-prod
  namespace: claims-ns
  labels:
    app: claims
spec:
  type: ClusterIP
  selector:
    app: claims
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000