name: build and deploy claims-app to AKS
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_RG: poc-rg
  ACR: vhacr
  AKS_RG: poc-rg
  AKS_NAME: claims
  CONTAINER_TAG: ${{ github.sha }}
  CONTAINER_NAME: claims
  DEPLOY_NS: claims-ns
  USERNAME: 'Nadeem Khalid'

jobs:
  # variables to be used in the build job
  reuse_variables:
    uses: nk1752/redirect-app/.github/workflows/variables.yml@main
    with:
      username: 'Nadeem Khalid'

  comapre:
    runs-on: ubuntu-latest
    steps:
      - name: shared variables
        run: echo `The value of the variable is ${{ env.USERNAME }}`
      - name: github.sha
        run: echo `github SHA -> ${{ github.sha }}`

  # build job
  build:
    runs-on: ubuntu-latest

    needs: [reuse_variables, comapre]

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: build and push image to ACR
        run: |
          az acr build \
          --image ${{ env.ACR }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_TAG }} \
          --registry ${{ env.ACR }} \
          -g ${{ env.ACR_RG }} \
          -f ./dockerfiles/Dockerfile.prod .

  # deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # setup kubectl
      - name: setup kubectl
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25' # Default version of kubelogin is latest

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.AKS_RG }}
          cluster-name: ${{ env.AKS_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          resource-group: ${{ env.AKS_RG }}
          namespace: ${{ env.DEPLOY_NS }}
          action: deploy
          strategy: basic  # basic | canary | blue-green
          # FQDN of the image to be deployed
          images: |
            ${{ env.ACR }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_TAG }}
          # modify the manifest file to point to the image
          manifests: |
            manifests/deployment.yml