name: build and deploy claims-app to AKS
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_RG: poc-rg
  ACR: vhacr
  AKS_RG: poc-rg
  AKS_NAME: claims
  CONTAINER_TAG: ${{ github.sha }}
  DEPLOY_NS: claims-ns
  USERNAME: 'Nadeem Khalid'

jobs:

  # variables to be used in the build job
  reuse_variables:
    
    uses: nk1752/redirect-app/.github/workflows/variables.yml@main
    with:
      username: 'Nadeem Khalid'
      
  comapre:
    runs-on: ubuntu-latest
    steps:
      - name: shared variables
        run: echo `The value of the variable is ${{ env.USERNAME }}`
      - name: github.sha
        run: echo `github SHA -> ${{ github.sha }}`

  # build job
  build:
    runs-on: ubuntu-latest
    
    needs: [reuse_variables, comapre]
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      